---
- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  scm: git

- name: infra-role-tinc
  src: git@github.com:status-im/infra-role-tinc.git
  scm: git

- name: infra-role-bootstrap
  src: git@github.com:status-im/infra-role-bootstrap.git
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  scm: git

# WARNING: Fails if python3 is the default
- name: mongodb-setup
  src: git@github.com:status-im/ansible-role-mongodb.git
  scm: git
